### PR TITLE
Cleanup & fixes

### LINKED ISSUE #18: How to reconstruct type from multiple locations?
I'm wondering if it's possible to reconstruct a type from multiple functions. For example, this function assigns the vtable but it does not use all fields.

Before reconstruct type:

image

After reconstruct type:

image

That works perfectly. However, it only creates the fields that are specifically used here.

Many more fields of this type are only used in other functions. Reconstruct type seems to just load the existing struct instead of adding newly discovered fields, resulting in weird gap_F8[44] fields. (v2 is a NetConnection *)

image

Does your plugin or IDA itself provide an easy way to solve this?

### PR DESCRIPTION
**Pull request by stek29**
- Reduce amount of warnings when building with clang (also fixes some issues/bugs spotted by those warnings)
- Make it build for both HexRays7 (IDA7.0) and HexRays8 (IDA8.0) by wrapping print1 calls in template and casting `callback` in install/remove HexRays callback
- Fix #18
- Show current type instead of "struct_name" when possible
- Allow Reconstruct Type when local variable (or arg) is selected, not just on expressions

### CODE REVIEW

File: src/HexRaysCodeXplorer/TypeReconstructor.cpp [hunk 1]
```diff
@@ -586,7 +586,7 @@ bool idaapi reconstruct_type_cb(void *ud)
 			type_builder_t type_bldr;
 			{
 				qstring s;
-				highl_expr->print1(&s, NULL);
+				print1hack(highl_expr, &s, NULL);
```
Comment (stek29) [inline src/HexRaysCodeXplorer/TypeReconstructor.cpp]: ugh this was not intended to be included in this commit
